### ISSUE TITLE
Tiny Threat - Growth Direction

### ISSUE THREAD

**Issue by Foodlenz** [RichSteini/Details-TBC-2.4.3#1]
Tiny Threat doesn't seem be following the growth direction setting. 
![image](https://github.com/RichSteini/Details-TBC-2.4.3/assets/72258441/3ef58ad4-92bc-4299-861c-8a92141ee016)
![image](https://github.com/RichSteini/Details-TBC-2.4.3/assets/72258441/422325d9-1fd8-4bdc-babf-cdaa73760579)

The setting seems to work fine with the standard damage done etc meters though.
![image](https://github.com/RichSteini/Details-TBC-2.4.3/assets/72258441/3224a240-1748-4920-8b2d-94dc9b4dc86a)

**Comment by RichSteini** [comment]
It is a plugin, so pretty sure that this is not a bug, i remember it being like that in tbcc too (maybe they have changed it in newer versions).
